### ISSUE TITLE
Twilio doesn't work

### ISSUE THREAD

**Issue by RamyAlshurafa** [katpas/inshallahapp#193]
Twilio service response with `authenticated`

**Comment by RamyAlshurafa** [comment]
Hi @Sarafallan 
For now, we fixed the facebook signing in issue, but when we logged in the main page and try other functionality we found that more 2 issues:
  - Twilio: this because you Twilio account exceed the 18$ messages amount, so they suspend the account and ask for activate billings.
   we have two options to fix this
     * pay for Twilio.
     * create a new account with a new number to receive the messages, this will give you about 220 free messages, then will be suspended again.
  - Google Map: #192 to fix this need to provide a billing method for google map (e.g credit card) and it will give you free 200$ monthly to use(about 28,000 monthly requests)

what do you think?

**Comment by thejoefriel** [comment]
@RamyAlshurafa - @Sarafallan doesn't really have another phone number to use. Do you mind letting her know the pricing set up on Twilio and how she can top it up please?

**Comment by RamyAlshurafa** [comment]
sorry for delay @thejoefriel 
here is Twilio pricing page https://www.twilio.com/sms/pricing/gb
in short words it cost `$0.04` per SMS
also she needs to pay `18$` she used previously

**Comment by Sarafallan** [comment]
Hi Ramy!
I've fixed Twilio now!
Thank you
Sara

**Comment by RamyAlshurafa** [comment]
Hi @Sarafallan 
thanks for updating, but we still get this message from Twilio 
`Your Twilio Account is currently suspended due to a lack of funds. Recharge your account and get back to making calls.`
are you sure you have upgraded it?

**Comment by Sarafallan** [comment]
Hi Rami,
Yes I upgraded it. The current balance is $5.44. Does it need to be more?
See below my billing overview screenshot. It does not say it's disabled.
Thanks,
Sara

[image: image.png]

**Comment by RamyAlshurafa** [comment]
@Sarafallan 
sorry but the image didn't appear here but in general could you send me the email and password for your account
maybe we use different accounts we use inshallahapp@gmail.com to log in to Twilio 
here is my email `ramyshurafa@hotmail.com`

**Comment by RamyAlshurafa** [comment]
Thanks a lot, @Sarafallan, and sorry for confusing 
yeah this could help
note I have deleted your comment because this repo is public and comments are exposed

**Comment by RamyAlshurafa** [comment]
Hey @Sarafallan 
I think everything is working fine now, so could you check it on Heroku https://inshallah.herokuapp.com/ and let us know if there is missed
also if you are happy with this then could you send the Godaddy account to set it up for the app?

**Comment by RamyAlshurafa** [comment]
Done!
